### ISSUE TITLE
RecyclerView crashes when scrolling around

### ISSUE THREAD

**Issue by ahmedre** [chrisbanes/cheesesquare#2]
i am guessing this is most likely a `RecyclerView` crash (and not something in the application), but filing it here anyhow and then if so, i guess maybe can open something on the android tracker.

```
E/MessageQueue-JNI( 1398): java.lang.NullPointerException
E/MessageQueue-JNI( 1398): 	at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1391)
E/MessageQueue-JNI( 1398): 	at android.support.v7.widget.RecyclerView.scrollBy(RecyclerView.java:1314)
E/MessageQueue-JNI( 1398): 	at android.support.v7.widget.RecyclerView.onGenericMotionEvent(RecyclerView.java:2289)
E/MessageQueue-JNI( 1398): 	at android.view.View.dispatchGenericMotionEventInternal(View.java:7801)
E/MessageQueue-JNI( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7782)
E/MessageQueue-JNI( 1398): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
E/MessageQueue-JNI( 1398): 	at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
E/MessageQueue-JNI( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7775)
E/MessageQueue-JNI( 1398): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
E/MessageQueue-JNI( 1398): 	at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
E/MessageQueue-JNI( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7775)
E/MessageQueue-JNI( 1398): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
E/MessageQueue-JNI( 1398): 	at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
E/MessageQueue-JNI( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7775)
E/MessageQueue-JNI( 1398): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
E/MessageQueue-JNI( 1398): 	at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
E/MessageQueue-JNI( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7775)
E/MessageQueue-JNI( 1398): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
E/MessageQueue-JNI( 1398): 	at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
E/MessageQueue-JNI( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7775)
E/MessageQueue-JNI( 1398): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
E/MessageQueue-JNI( 1398): 	at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
E/MessageQueue-JNI( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7775)
E/MessageQueue-JNI( 1398): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
E/MessageQueue-JNI( 1398): 	at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
E/MessageQueue-JNI( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7775)
E/MessageQueue-JNI( 1398): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
E/MessageQueue-JNI( 1398): 	at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
E/MessageQueue-JNI( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7775)
E/MessageQueue-JNI( 1398): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchGenericMotionEvent(PhoneWindow.java:2076)
E/MessageQueue-JNI( 1398): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1525)
E/MessageQueue-JNI( 1398): 	at android.app.Activity.dispatchGenericMotionEvent(Activity.java:2494)
E/MessageQueue-JNI( 1398): 	at android.support.v7.internal.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:69)
E/MessageQueue-JNI( 1398): 	at android.support.v7.internal.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:69)
E/MessageQueue-JNI( 1398): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchGenericMotionEvent(PhoneWindow.java:2030)
E/MessageQueue-JNI( 1398): 	at android.view.View.dispatchPointerEvent(View.java:7888)
E/MessageQueue-JNI( 1398): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3947)
E/MessageQueue-JNI( 1398): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3826)
E/MessageQueue-JNI( 1398): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
E/MessageQueue-JNI( 1398): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
E/MessageQueue-JNI( 1398): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
E/MessageQueue-JNI( 1398): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3518)
E/MessageQueue-JNI( 1398): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
E/MessageQueue-JNI( 1398): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3575)
E/MessageQueue-JNI( 1398): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
E/MessageQueue-JNI( 1398): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
E/MessageQueue-JNI( 1398): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
E/MessageQueue-JNI( 1398): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
E/MessageQueue-JNI( 1398): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
E/MessageQueue-JNI( 1398): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5532)
E/MessageQueue-JNI( 1398): 	at android.view.ViewRootImpl.doProcessInputEve
D/AndroidRuntime( 1398): Shutting down VM
W/dalvikvm( 1398): threadid=1: thread exiting with uncaught exception (group=0xa4ce3b20)
E/AndroidRuntime( 1398): FATAL EXCEPTION: main
E/AndroidRuntime( 1398): Process: com.support.android.designlibdemo, PID: 1398
E/AndroidRuntime( 1398): java.lang.NullPointerException
E/AndroidRuntime( 1398): 	at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1391)
E/AndroidRuntime( 1398): 	at android.support.v7.widget.RecyclerView.scrollBy(RecyclerView.java:1314)
E/AndroidRuntime( 1398): 	at android.support.v7.widget.RecyclerView.onGenericMotionEvent(RecyclerView.java:2289)
E/AndroidRuntime( 1398): 	at android.view.View.dispatchGenericMotionEventInternal(View.java:7801)
E/AndroidRuntime( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7782)
E/AndroidRuntime( 1398): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
E/AndroidRuntime( 1398): 	at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
E/AndroidRuntime( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7775)
E/AndroidRuntime( 1398): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
E/AndroidRuntime( 1398): 	at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
E/AndroidRuntime( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7775)
E/AndroidRuntime( 1398): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
E/AndroidRuntime( 1398): 	at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
E/AndroidRuntime( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7775)
E/AndroidRuntime( 1398): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
E/AndroidRuntime( 1398): 	at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
E/AndroidRuntime( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7775)
E/AndroidRuntime( 1398): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
E/AndroidRuntime( 1398): 	at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
E/AndroidRuntime( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7775)
E/AndroidRuntime( 1398): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
E/AndroidRuntime( 1398): 	at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
E/AndroidRuntime( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7775)
E/AndroidRuntime( 1398): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
E/AndroidRuntime( 1398): 	at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
E/AndroidRuntime( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7775)
E/AndroidRuntime( 1398): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
E/AndroidRuntime( 1398): 	at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
E/AndroidRuntime( 1398): 	at android.view.View.dispatchGenericMotionEvent(View.java:7775)
E/AndroidRuntime( 1398): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchGenericMotionEvent(PhoneWindow.java:2076)
E/AndroidRuntime( 1398): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1525)
E/AndroidRuntime( 1398): 	at android.app.Activity.dispatchGenericMotionEvent(Activity.java:2494)
E/AndroidRuntime( 1398): 	at android.support.v7.internal.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:69)
E/AndroidRuntime( 1398): 	at android.support.v7.internal.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:69)
E/AndroidRuntime( 1398): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchGenericMotionEvent(PhoneWindow.java:2030)
E/AndroidRuntime( 1398): 	at android.view.View.dispatchPointerEvent(View.java:7888)
E/AndroidRuntime( 1398): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3947)
E/AndroidRuntime( 1398): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3826)
E/AndroidRuntime( 1398): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
E/AndroidRuntime( 1398): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
E/AndroidRuntime( 1398): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
E/AndroidRuntime( 1398): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3518)
E/AndroidRuntime( 1398): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
E/AndroidRuntime( 1398): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3575)
E/AndroidRuntime( 1398): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
E/AndroidRuntime( 1398): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
E/AndroidRuntime( 1398): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
E/AndroidRuntime( 1398): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
E/AndroidRuntime( 1398): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
E/AndroidRuntime( 1398): 	at android.view.ViewRootImpl.deliverInputEve
W/ActivityManager(  502):   Force finishing activity com.support.android.designlibdemo/.MainActivity
D/dalvikvm(  502): GC_FOR_ALLOC freed 601K, 22% free 8448K/10816K, paused 6ms, total 6ms
I/dalvikvm-heap(  502): Grow heap (frag case) to 8.664MB for 380492-byte allocation
D/dalvikvm(  502): GC_FOR_ALLOC freed 3K, 22% free 8816K/11188K, paused 4ms, total 4ms
D/dalvikvm(  502): GC_FOR_ALLOC freed 2K, 22% free 8814K/11188K, paused 4ms, total 4ms
I/dalvikvm-heap(  502): Grow heap (frag case) to 9.021MB for 380492-byte allocation
D/dalvikvm(  502): GC_FOR_ALLOC freed <1K, 21% free 9185K/11560K, paused 6ms, total 6ms
D/MobileDataStateTracker(  502): default: setPolicyDataEnable(enabled=true)
D/MobileDataStateTracker(  502): default: setPolicyDataEnable(enabled=true)
W/ActivityManager(  502): Activity pause timeout for ActivityRec
```

**Comment by ahmedre** [comment]
since this seems to be a bug in `RecyclerView`, filed https://code.google.com/p/android/issues/detail?id=174981 and closing this.
